import { Movie, Genre, CastMember, Review, User } from '@/types';

export const genres: Genre[] = [
  { id: 28, name: 'Action' },
  { id: 12, name: 'Adventure' },
  { id: 16, name: 'Animation' },
  { id: 35, name: 'Comedy' },
  { id: 80, name: 'Crime' },
  { id: 99, name: 'Documentary' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Family' },
  { id: 14, name: 'Fantasy' },
  { id: 36, name: 'History' },
  { id: 27, name: 'Horror' },
  { id: 10402, name: 'Music' },
  { id: 9648, name: 'Mystery' },
  { id: 10749, name: 'Romance' },
  { id: 878, name: 'Science Fiction' },
  { id: 10770, name: 'TV Movie' },
  { id: 53, name: 'Thriller' },
  { id: 10752, name: 'War' },
  { id: 37, name: 'Western' },
];

const cast1: CastMember[] = [
  { id: 1, name: 'Robert Downey Jr.', character: 'Tony Stark', profile_path: 'https://image.tmdb.org/t/p/w185/5qHoazZiaLe7oFBok7XlUhg96f2.jpg' },
  { id: 2, name: 'Chris Evans', character: 'Steve Rogers', profile_path: 'https://image.tmdb.org/t/p/w185/3bOGNs2rFLCF59sYJlPNxJbqZQB.jpg' },
  { id: 3, name: 'Scarlett Johansson', character: 'Natasha Romanoff', profile_path: 'https://image.tmdb.org/t/p/w185/6N7XhcK0xvzvnWviByQqK3ysHhy.jpg' },
  { id: 4, name: 'Chris Hemsworth', character: 'Thor', profile_path: 'https://image.tmdb.org/t/p/w185/x5jJK6bdHqqvN3TQQOhK1jJvYhP.jpg' },
  { id: 5, name: 'Mark Ruffalo', character: 'Bruce Banner', profile_path: 'https://image.tmdb.org/t/p/w185/6Ppxc5mSfvMDJ3i8WYlfk9P3J3e.jpg' },
];

const cast2: CastMember[] = [
  { id: 6, name: 'Daniel Craig', character: 'James Bond', profile_path: 'https://image.tmdb.org/t/p/w185/3xkxL2a4F4ThRZ2sL4jFDBU7a5.jpg' },
  { id: 7, name: 'Léa Seydoux', character: 'Madeleine Swann', profile_path: 'https://image.tmdb.org/t/p/w185/5E1pC57aKoVfL4g1J6mbob6a9rR.jpg' },
  { id: 8, name: 'Rami Malek', character: 'Safin', profile_path: 'https://image.tmdb.org/t/p/w185/i44w5IlK3q4cETOq4PGQDJMQvfN.jpg' },
  { id: 9, name: 'Ana de Armas', character: 'Paloma', profile_path: 'https://image.tmdb.org/t/p/w185/3vxvsmYLTf4jnr163SUlBIw51ee.jpg' },
  { id: 10, name: 'Ben Whishaw', character: 'Q', profile_path: 'https://image.tmdb.org/t/p/w185/lH5JzB2J8y8I5lYd3oJ7l3F5U5Y.jpg' },
];

const cast3: CastMember[] = [
  { id: 11, name: 'Leonardo DiCaprio', character: 'Dom Cobb', profile_path: 'https://image.tmdb.org/t/p/w185/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg' },
  { id: 12, name: 'Joseph Gordon-Levitt', character: 'Arthur', profile_path: 'https://image.tmdb.org/t/p/w185/zvPmsxi8J4gZPUlfo4WJIHF3Fbg.jpg' },
  { id: 13, name: 'Elliot Page', character: 'Ariadne', profile_path: 'https://image.tmdb.org/t/p/w185/iIKSrJ7jLijKePuKKZdNpoEoZoP.jpg' },
  { id: 14, name: 'Tom Hardy', character: 'Eames', profile_path: 'https://image.tmdb.org/t/p/w185/qcL8Ngq0qqqPflv1i1e9l3lDJ5C.jpg' },
  { id: 15, name: 'Ken Watanabe', character: 'Saito', profile_path: 'https://image.tmdb.org/t/p/w185/psAXOYp9SBOXvg6AXzARDedNQ9P.jpg' },
];

const posterBase = 'https://image.tmdb.org/t/p/w500';
const backdropBase = 'https://image.tmdb.org/t/p/original';

export const mockMovies: Movie[] = [
  {
    id: 1,
    title: 'Avengers: Endgame',
    overview: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
    poster_path: `${posterBase}/or06FN3Dka5tukK1e9sl16pB3iy.jpg`,
    backdrop_path: `${backdropBase}/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg`,
    release_date: '2019-04-24',
    vote_average: 8.4,
    vote_count: 21000,
    genre_ids: [28, 878, 12],
    genres: [genres[0], genres[14], genres[1]],
    runtime: 181,
    tagline: 'Avenge the fallen.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/TcMBFSGVi1c',
    cast: cast1,
  },
  {
    id: 2,
    title: 'No Time to Die',
    overview: 'James Bond has left active service. His peace is short-lived when Felix Leiter, an old ally from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
    poster_path: `${posterBase}/qJ2tW6WMUDux911r6m7haRef0WH.jpg`,
    backdrop_path: `${backdropBase}/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg`,
    release_date: '2021-09-29',
    vote_average: 7.5,
    vote_count: 4500,
    genre_ids: [28, 12, 53],
    genres: [genres[0], genres[1], genres[17]],
    runtime: 163,
    tagline: 'The greatest secret. One last mission.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/BIhNsAt7PIE',
    cast: cast2,
  },
  {
    id: 3,
    title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    poster_path: `${posterBase}/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg`,
    backdrop_path: `${backdropBase}/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg`,
    release_date: '2010-07-15',
    vote_average: 8.8,
    vote_count: 32000,
    genre_ids: [28, 878, 12],
    genres: [genres[0], genres[14], genres[1]],
    runtime: 148,
    tagline: 'Your mind is the scene of the crime.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/YoHD9XEInc0',
    cast: cast3,
  },
  {
    id: 4,
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    poster_path: `${posterBase}/qJ2tW6WMUDux911r6m7haRef0WH.jpg`,
    backdrop_path: `${backdropBase}/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg`,
    release_date: '2008-07-14',
    vote_average: 8.5,
    vote_count: 28000,
    genre_ids: [28, 80, 18],
    genres: [genres[0], genres[4], genres[6]],
    runtime: 152,
    tagline: 'Why so serious?',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/EXeTwQWrcwY',
    cast: [],
  },
  {
    id: 5,
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: `${posterBase}/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg`,
    backdrop_path: `${backdropBase}/xJHokMbljvjADYdit5fK5VQsXEG.jpg`,
    release_date: '2014-11-05',
    vote_average: 8.6,
    vote_count: 31000,
    genre_ids: [878, 18, 12],
    genres: [genres[14], genres[6], genres[1]],
    runtime: 169,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/zSWdZVtXT7E',
    cast: [],
  },
  {
    id: 6,
    title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    poster_path: `${posterBase}/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg`,
    backdrop_path: `${backdropBase}/xJHokMbljvjADYdit5fK5VQsXEG.jpg`,
    release_date: '2024-02-27',
    vote_average: 8.6,
    vote_count: 4500,
    genre_ids: [878, 12],
    genres: [genres[14], genres[1]],
    runtime: 166,
    tagline: 'Long live the fighters.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/Way9Dexny3w',
    cast: [],
  },
  {
    id: 7,
    title: 'Oppenheimer',
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    poster_path: `${posterBase}/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg`,
    backdrop_path: `${backdropBase}/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg`,
    release_date: '2023-07-19',
    vote_average: 8.4,
    vote_count: 7000,
    genre_ids: [18, 36],
    genres: [genres[6], genres[9]],
    runtime: 180,
    tagline: 'Worlds collide.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/uYPbbksJxIg',
    cast: [],
  },
  {
    id: 8,
    title: 'Spider-Man: Across the Spider-Verse',
    overview: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    poster_path: `${posterBase}/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg`,
    backdrop_path: `${backdropBase}/nHf61UzkfFno5X1ofIhugCPus2R.jpg`,
    release_date: '2023-05-31',
    vote_average: 8.5,
    vote_count: 5000,
    genre_ids: [16, 12, 28],
    genres: [genres[2], genres[1], genres[0]],
    runtime: 140,
    tagline: 'Enter a universe where anything is possible.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/shW9i6k8cB0',
    cast: [],
  },
  {
    id: 9,
    title: 'The Matrix',
    overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    poster_path: `${posterBase}/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg`,
    backdrop_path: `${backdropBase}/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg`,
    release_date: '1999-03-30',
    vote_average: 8.2,
    vote_count: 24000,
    genre_ids: [878, 28],
    genres: [genres[14], genres[0]],
    runtime: 136,
    tagline: 'Free your mind.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/vKQi3bBA1y8',
    cast: [],
  },
  {
    id: 10,
    title: 'Parasite',
    overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
    poster_path: `${posterBase}/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg`,
    backdrop_path: `${backdropBase}/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg`,
    release_date: '2019-05-30',
    vote_average: 8.5,
    vote_count: 15000,
    genre_ids: [35, 53, 18],
    genres: [genres[3], genres[17], genres[6]],
    runtime: 133,
    tagline: 'Act like you own the place.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/5xH0HfJHsaY',
    cast: [],
  },
  {
    id: 11,
    title: 'Joker',
    overview: 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
    poster_path: `${posterBase}/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg`,
    backdrop_path: `${backdropBase}/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg`,
    release_date: '2019-10-01',
    vote_average: 8.2,
    vote_count: 20000,
    genre_ids: [80, 18, 53],
    genres: [genres[4], genres[6], genres[17]],
    runtime: 122,
    tagline: 'Put on a happy face.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/zAGVQLHvwOY',
    cast: [],
  },
  {
    id: 12,
    title: 'The Shawshank Redemption',
    overview: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    poster_path: `${posterBase}/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg`,
    backdrop_path: `${backdropBase}/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg`,
    release_date: '1994-09-23',
    vote_average: 8.7,
    vote_count: 23000,
    genre_ids: [18, 80],
    genres: [genres[6], genres[4]],
    runtime: 142,
    tagline: 'Fear can hold you prisoner. Hope can set you free.',
    status: 'Released',
    trailer_url: 'https://www.youtube.com/embed/6hB3S9bIaco',
    cast: [],
  },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    movie_id: 1,
    user: { id: 1, username: 'moviebuff', email: 'moviebuff@example.com', avatar: 'https://i.pravatar.cc/150?img=1' },
    rating: 5,
    content: 'Absolutely mind-blowing! The culmination of 10 years of Marvel storytelling. The emotional weight at the end had me in tears.',
    created_at: '2019-04-26T10:00:00Z',
  },
  {
    id: 2,
    movie_id: 1,
    user: { id: 2, username: 'cinemalover', email: 'cinema@example.com', avatar: 'https://i.pravatar.cc/150?img=2' },
    rating: 4,
    content: 'Great movie but the runtime is a bit too long. Still, the payoff was totally worth it!',
    created_at: '2019-04-27T15:30:00Z',
  },
  {
    id: 3,
    movie_id: 3,
    user: { id: 3, username: 'filmcritic', email: 'critic@example.com', avatar: 'https://i.pravatar.cc/150?img=3' },
    rating: 5,
    content: 'A masterpiece of cinema. Nolan\'s direction is flawless and the concept is executed perfectly. One of the best films of the decade.',
    created_at: '2010-07-16T12:00:00Z',
  },
  {
    id: 4,
    movie_id: 5,
    user: { id: 1, username: 'moviebuff', email: 'moviebuff@example.com', avatar: 'https://i.pravatar.cc/150?img=1' },
    rating: 5,
    content: 'Visually stunning and emotionally resonant. The soundtrack by Hans Zimmer is incredible.',
    created_at: '2014-11-07T09:00:00Z',
  },
  {
    id: 5,
    movie_id: 10,
    user: { id: 4, username: 'arthousefan', email: 'arthouse@example.com', avatar: 'https://i.pravatar.cc/150?img=4' },
    rating: 5,
    content: 'Bong Joon-ho\'s masterpiece! A brilliant social commentary wrapped in a thriller. The cinematography is gorgeous.',
    created_at: '2019-06-02T18:00:00Z',
  },
];

export const mockUser: User = {
  id: 1,
  username: 'johndoe',
  email: 'john@example.com',
  avatar: 'https://i.pravatar.cc/150?img=1',
  created_at: '2023-01-01T00:00:00Z',
};
